apiVersion: apps/v1
kind: Deployment
metadata:
  name: haein05
  namespace: default
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: haein05
  template:
    metadata:
      name: haein05
      labels:
        app: haein05
    spec:
      containers:
      - name: haein05
        image: haein05/cit270
        volumeMounts:
        - name: ssl
          mountPath: "/usr/src/app/SSL"
        command: ["npm"]
        args: ["run" , "start"]
        env:
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: redis-secrets-haein
                key: REDIS_PASS
        resources:
          requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
      - name: ssl
        secret: 
          secretName: ssl.secret.haein
---
apiVersion: v1
kind: Service
metadata: 
  name: haein05-loadbalancer
spec: 
  selector: 
    app: haein05
  type: LoadBalancer
  ports: 
  - port: 443
    targetPort: 443
